# Generated by Django 5.2.5 on 2025-08-23 15:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sdsa_owner', models.ForeignKey(limit_choices_to={'role': 'SDSA'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='FCP code must be in format: XX0000 (e.g., UG0249)', regex='^[A-Z]{2}\\d{4}$')])),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_collection_centre', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcps', to='org.cluster')),
            ],
            options={
                'ordering': ['cluster', 'code'],
                'unique_together': {('cluster', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CollectionCentreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CC'}, on_delete=django.db.models.deletion.CASCADE, related_name='collection_centre', to=settings.AUTH_USER_MODEL)),
                ('fcp', models.OneToOneField(limit_choices_to={'is_collection_centre': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cc_user', to='org.fcp')),
            ],
            options={
                'verbose_name': 'Collection Centre User',
                'verbose_name_plural': 'Collection Centre Users',
            },
        ),
    ]
