# Generated by Django 5.2.5 on 2025-08-23 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Outgoing (SDSA → Collection Centre)'), ('RET', 'Return (Collection Centre → SDSA)')], editable=False, max_length=3)),
                ('estimated_delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created/Sent'), ('RECEIVED_CC', 'Received at Collection Centre'), ('DISTRIBUTED', 'Distributed to FCPs'), ('RECEIVED_NO', 'Received at National Office'), ('POSTED', 'Posted')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='org.cluster')),
                ('collection_centre', models.ForeignKey(limit_choices_to={'is_collection_centre': True}, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='org.fcp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_planned', models.PositiveIntegerField()),
                ('qty_received', models.PositiveIntegerField(blank=True, null=True)),
                ('discrepancy_note', models.TextField(blank=True)),
                ('fcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='org.fcp')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment')),
            ],
            options={
                'ordering': ['fcp__code'],
                'unique_together': {('shipment', 'fcp')},
            },
        ),
    ]
